name: hitrip
description: A travel app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.5
  animated_bottom_navigation_bar: ^1.2.0
  # flutter_icons:
  #   git:
  #     url: https://github.com/adarsh-technocrat/flutter-icons
  # md2_tab_indicator:
  #   git:
  #     url: https://github.com/westdabestdb/md2_tab_indicator
  url_launcher: ^6.1.10
  # fluttertoast: ^8.2.1
  cached_network_image: ^3.2.3
  line_icons: ^2.0.1
  carousel_pro_nullsafety: ^2.0.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  sliding_up_panel: ^2.0.0+1
  flutter_launcher_icons: ^0.13.0
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  md2_tab_indicator: ^1.0.2
  flutter_facebook_auth: ^5.0.11
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Muli
      fonts:
        # - asset: fonts/Montserrat-Light.ttf
        #   weight: 400
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800


    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900


    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
